// MV3 service worker — the only place in this extension that talks to the
// local companion service. content.js relays every companion-service call
// through here via chrome.runtime.sendMessage, rather than fetching
// directly, so there's one place that knows SHARED_SECRET.

// companion-config.js is generated by companion-service/setup.js (and is
// gitignored) — it sets self.COMPANION_CONFIG = { serviceBaseUrl,
// sharedSecret } to match companion-service/config.json. The secret is
// the companion service's actual access check — see the comment on the
// server-side middleware (companion-service/server.ts) for why an
// Origin-header check doesn't work here: fetches to a host declared in
// this extension's host_permissions (127.0.0.1) are CORS-exempt and
// Chrome doesn't send an Origin header for them.
try {
  importScripts("companion-config.js");
} catch {
  // Setup hasn't been run for this copy yet — callService explains.
}
const COMPANION_CONFIG = self.COMPANION_CONFIG || null;
const SERVICE_BASE_URL = COMPANION_CONFIG?.serviceBaseUrl || "http://127.0.0.1:8787";
const SHARED_SECRET = COMPANION_CONFIG?.sharedSecret || "";
const FIX_HINT =
  "Run the installer again (see the README), or `npm run doctor` in " +
  "~/ai-dev-companion/companion-service to see exactly what's wrong.";

// Relays the current page's browser session to the companion service so a
// feature can act as the logged-in user (e.g. Jira SSO) without any
// credential being configured. document.cookie in content.js can't see
// HttpOnly session cookies (JSESSIONID, SSO/seraph cookies) — chrome.cookies
// can, which is why this lives here rather than being read page-side and
// sent up as a normal fetch. These headers only ever travel to 127.0.0.1 on
// this machine (behind the X-Companion-Secret check below), and the
// companion service only ever relays a cookie back out to the same origin
// it came from (see core/atlassian.ts) — never anywhere else.
async function relayHeadersFor(pageUrl) {
  if (!pageUrl) return {};
  let cookies;
  try {
    cookies = await chrome.cookies.getAll({ url: pageUrl });
  } catch {
    return {};
  }
  if (!cookies || cookies.length === 0) return {};
  return {
    "X-Relay-Cookie": cookies.map((c) => `${c.name}=${c.value}`).join("; "),
    "X-Relay-Origin": new URL(pageUrl).origin,
  };
}

async function callService(path, { method = "GET", body, pageUrl } = {}) {
  if (!SHARED_SECRET) {
    throw new Error(
      "The extension isn't connected to the companion service yet: companion-config.js is missing " +
        "from the extension folder, which means setup hasn't finished for this copy. " +
        `${FIX_HINT} Then reload the extension at chrome://extensions.`,
    );
  }
  let res;
  try {
    res = await fetch(`${SERVICE_BASE_URL}${path}`, {
      method,
      headers: {
        "X-Companion-Secret": SHARED_SECRET,
        ...(await relayHeadersFor(pageUrl)),
        ...(body !== undefined ? { "Content-Type": "application/json" } : {}),
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
  } catch (err) {
    throw new Error(
      `Could not reach the companion service at ${SERVICE_BASE_URL} — it isn't running. ${FIX_HINT} ` +
        `(${err.message})`,
    );
  }
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(data.error || `companion service returned HTTP ${res.status}`);
    // Structured errors (e.g. code "repo-not-found" with project/repo)
    // travel back to content.js so it can offer a fix, not just a message.
    // status rides along too — /jobs/:jobId/open-in-claude-code's resume
    // path (open-in-editor.js) tells a 410 (session expired, recoverable
    // by opening a fresh terminal instead) apart from a 409/400 (both
    // just error messages) only by status code, since all three send the
    // same { error } shape.
    err.details = { ...data, status: res.status };
    throw err;
  }
  return data;
}

// Opt-in (Settings → Browser sessions → Keep browser sessions warm): every
// 5 minutes, re-send each configured host's cookies so the companion's
// in-memory session vault (core/session-vault.js) stays fresh for MCP
// calls from terminal Claude. relayHeadersFor relays ONE origin's cookies
// per request, so it's one /extension/hello per host — never a combined
// header. A host with no cookies in this browser is skipped.
const HEARTBEAT_ALARM = "session-heartbeat";

async function syncHeartbeat() {
  const { heartbeat, hosts } = await callService("/extension/session-hosts");
  if (!heartbeat) {
    await chrome.alarms.clear(HEARTBEAT_ALARM);
    return [];
  }
  if (!(await chrome.alarms.get(HEARTBEAT_ALARM))) {
    chrome.alarms.create(HEARTBEAT_ALARM, { periodInMinutes: 5 });
  }
  return Array.isArray(hosts) ? hosts : [];
}

async function relayHosts(hosts) {
  for (const host of hosts) {
    const pageUrl = `${host}/`;
    // Only hosts in this manifest's host_permissions can have their cookies
    // read; chrome.cookies.getAll returns [] for any other host, so
    // relayHeadersFor produces no X-Relay-Cookie and the host is skipped
    // below. That's intended — the heartbeat can only refresh sessions this
    // browser is actually allowed to see.
    const relay = await relayHeadersFor(pageUrl);
    if (!relay["X-Relay-Cookie"]) continue;
    await callService("/extension/hello", {
      method: "POST",
      body: { version: chrome.runtime.getManifest().version, heartbeat: true },
      pageUrl,
    }).catch(() => {});
  }
}

async function sendHeartbeat() {
  await relayHosts(await syncHeartbeat());
}

// Features that read more than the current page's site (the digest reads
// Bitbucket and Jira) need every site's session, not just this tab's. Best
// effort: a site with no cookies here is skipped and the service falls back
// to a saved token, as before.
async function relayAllSessions() {
  try {
    const { hosts } = await callService("/extension/session-origins");
    await relayHosts(Array.isArray(hosts) ? hosts : []);
  } catch {
    // the start call below reports any real problem
  }
}

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name === HEARTBEAT_ALARM) void sendHeartbeat().catch(() => {});
  if (alarm.name === INBOX_ALARM) void announceInbox().catch(() => {});
});

async function handle(message) {
  switch (message.type) {
    case "list-features":
      return { features: await callService("/features") };
    case "get-targets":
      return { targets: await callService("/targets") };
    case "pr-status": {
      // What the companion reads off the git host about the PR on the page. No page cookies are sent: for a
      // host like GitHub they are no use to it, and the companion authenticates with its own saved token.
      const query = new URLSearchParams({ project: String(message.project), repo: String(message.repo), prId: String(message.prId) });
      return { status: await callService(`/prs/status?${query}`) };
    }
    case "start":
      if (message.featureId === "digest") await relayAllSessions();
      return {
        job: await callService(`/features/${message.featureId}/start`, {
          method: "POST",
          body: message.payload,
          pageUrl: message.pageUrl,
        }),
      };
    case "status":
      return { job: await callService(`/status/${message.jobId}`) };
    case "analysis-saved":
      return await callService(`/analysis-cache/${encodeURIComponent(message.issueKey)}`);
    case "summary-saved":
      return await callService(`/summary-cache/${encodeURIComponent(message.issueKey)}`);
    // The three cases below are Task 6's Claude-Code-started-it flow: an
    // MCP tool may have already created a "pending-start" job for this
    // page's scopeKey before the page ever asked for one (lookup-job),
    // and a browser click either turns it into a real job (start-pending)
    // or discards it (dismiss-pending) — see server.ts's /jobs/... routes.
    case "lookup-job":
      // GET /jobs/lookup already answers { job } itself; no reshaping needed.
      return await callService(
        `/jobs/lookup?${new URLSearchParams({ scopeKey: message.scopeKey, featureId: message.featureId })}`,
      );
    case "start-pending":
      return {
        job: await callService(`/jobs/${message.jobId}/start`, {
          method: "POST",
          pageUrl: message.pageUrl,
        }),
      };
    case "dismiss-pending":
      // POST /jobs/:jobId/dismiss already answers { ok: true } itself.
      return await callService(`/jobs/${message.jobId}/dismiss`, { method: "POST" });
    case "approve":
      return {
        job: await callService(`/features/${message.featureId}/${message.jobId}/approve`, {
          method: "POST",
          body: message.payload,
          pageUrl: message.pageUrl,
        }),
      };
    case "cancel":
      return {
        job: await callService(`/features/${message.featureId}/${message.jobId}/cancel`, {
          method: "POST",
          pageUrl: message.pageUrl,
        }),
      };
    case "reject":
      return {
        job: await callService(`/features/${message.featureId}/${message.jobId}/reject`, {
          method: "POST",
          pageUrl: message.pageUrl,
        }),
      };
    case "post-comment":
      return await callService(`/features/${message.featureId}/${message.jobId}/post-comment`, {
        method: "POST",
        body: message.body !== undefined ? { body: message.body } : undefined,
        pageUrl: message.pageUrl,
      });
    case "refresh-diff":
      // Re-reads a resolve-conflict job's worktree instead of the stale
      // diff snapshot taken when the job first landed (features.js's
      // footerActions entry). No body; cookies relay the same way
      // approve's do, in case the endpoint ever needs an authed re-check.
      return {
        job: await callService(`/features/${message.featureId}/${message.jobId}/refresh-diff`, {
          method: "POST",
          pageUrl: message.pageUrl,
        }),
      };
    case "feature-action":
      // A feature's named action on one of its jobs (core/jobs.ts's
      // Feature.actions): e.g. the ticket workspace's open-worktree, or
      // Ticket to PR's draft-pr. The service checks the name and anything
      // the body names against the job's own data.
      return await callService(
        `/features/${encodeURIComponent(message.featureId)}/${encodeURIComponent(message.jobId)}/actions/${encodeURIComponent(message.action)}`,
        { method: "POST", body: message.body, pageUrl: message.pageUrl },
      );
    case "open-in-claude-code":
      // message.body carries {resume: true} for a resumed session (see
      // core/resume.js); callers that omit it (the plain "open a
      // terminal here" case) keep getting no body, same as before.
      return await callService(`/jobs/${message.jobId}/open-in-claude-code`, {
        method: "POST",
        body: message.body,
      });
    case "choose-repo":
      return await callService("/repos/choose", {
        method: "POST",
        body: { project: message.project, repo: message.repo },
      });
    case "notifications-get":
      // GET /notifications already answers { items, unseen, background }.
      return await callService("/notifications");
    case "notifications-seen":
      return await callService("/notifications/seen", {
        method: "POST",
        body: message.all === true ? { all: true } : { ids: message.ids },
      });
    case "notification-open":
      return await callService(`/notifications/${encodeURIComponent(message.id)}/open`, { method: "POST" });
    case "open-location":
      return await callService("/open-location", {
        method: "POST",
        body: { text: message.text, pageUrl: message.pageUrl },
        pageUrl: message.pageUrl,
      });
    case "clone-repo":
      return {
        job: await callService("/repos/clone", {
          method: "POST",
          body: { project: message.project, repo: message.repo },
          pageUrl: message.pageUrl,
        }),
      };
    case "update-info":
      return {
        info: await callService(`/update${message.refresh ? "?refresh=1" : ""}`),
        extensionVersion: chrome.runtime.getManifest().version,
      };
    case "update-apply":
      return { status: await callService("/update/apply", { method: "POST" }) };
    case "settings-get":
      return { view: await callService("/settings") };
    case "settings-save": {
      const view = await callService("/settings", { method: "PUT", body: message.settings });
      // Picks up a heartbeat toggle immediately, instead of waiting up to 5
      // minutes for the next alarm to notice sessionCache.heartbeat changed.
      void sendHeartbeat().catch(() => {});
      return { view };
    }
    case "data-folder-get":
      return { usage: await callService("/data-folder") };
    case "data-folder-open":
      return await callService("/data-folder/open", { method: "POST" });
    case "data-folder-purge":
      return await callService("/data-folder/purge", { method: "POST" });
    case "settings-restart":
      return await callService("/settings/restart", { method: "POST", body: { force: !!message.force } });
    case "reload-extension":
      // After the updater has replaced this unpacked extension's files on
      // disk; reloading picks them up. Deferred so this reply still arrives.
      setTimeout(() => chrome.runtime.reload(), 300);
      return { ok: true };
    default:
      throw new Error(`unknown message type: ${message.type}`);
  }
}

// Setup waits for this (GET /extension/hello) to know Chrome is connected.
function sayHello() {
  if (!SHARED_SECRET) return;
  callService("/extension/hello", {
    method: "POST",
    body: { version: chrome.runtime.getManifest().version },
  })
    .then(() => void sendHeartbeat().catch(() => {}))
    .catch(() => {});
}

chrome.runtime.onInstalled.addListener(sayHello);
chrome.runtime.onStartup.addListener(sayHello);

// ---- Background work: one Chrome notification per batch the companion plans ----
// Every minute, ask the companion what (if anything) to announce: it batches
// (at most one every notify.minIntervalMinutes, sooner for an urgent item)
// and holds everything in quiet hours — see companion-service/core/notifications.js.
const INBOX_ALARM = "companion-inbox";
const INBOX_NOTIFICATION_PREFIX = "pai-inbox:";

function ensureInboxAlarm() {
  chrome.alarms.get(INBOX_ALARM, (existing) => {
    if (!existing) chrome.alarms.create(INBOX_ALARM, { periodInMinutes: 1 });
  });
}
chrome.runtime.onInstalled.addListener(ensureInboxAlarm);
chrome.runtime.onStartup.addListener(ensureInboxAlarm);
ensureInboxAlarm();

async function announceInbox() {
  if (!SHARED_SECRET) return;
  const { announce } = await callService("/notifications/announce", { method: "POST" });
  if (!announce || !Array.isArray(announce.ids) || announce.ids.length === 0) return;
  const id = `${INBOX_NOTIFICATION_PREFIX}${Date.now()}`;
  // Only an https page is ever opened from a notification click.
  let url = null;
  try {
    url = announce.url && new URL(announce.url).protocol === "https:" ? announce.url : null;
  } catch {
    url = null;
  }
  await chrome.storage.session.set({ [id]: { url, ids: announce.ids.slice(0, 100) } });
  // The service has already counted these as announced; if Chrome refuses
  // the notification, drop the click data with it rather than leave it behind.
  const dropOnFailure = () => {
    if (chrome.runtime.lastError) chrome.storage.session.remove(id);
  };
  try {
    chrome.notifications.create(
      id,
      {
        type: "basic",
        iconUrl: NOTIFICATION_ICON,
        title: String(announce.title || "AI Dev Companion").slice(0, 120),
        message: String(announce.message || "").slice(0, 400),
        priority: announce.urgent ? 2 : 0,
      },
      dropOnFailure,
    );
  } catch {
    await chrome.storage.session.remove(id);
  }
}

chrome.notifications.onClicked.addListener((notificationId) => {
  if (!notificationId.startsWith(INBOX_NOTIFICATION_PREFIX)) return;
  chrome.storage.session.get([notificationId], (stored) => {
    const entry = stored[notificationId];
    chrome.notifications.clear(notificationId);
    chrome.storage.session.remove(notificationId);
    if (!entry) return;
    if (entry.ids.length === 1) void callService(`/notifications/${encodeURIComponent(entry.ids[0])}/open`, { method: "POST" }).catch(() => {});
    if (entry.url) chrome.tabs.create({ url: entry.url });
  });
});

// ---- Right-click "Open in editor" on a selected stack-trace line ----
const OPEN_IN_EDITOR_MENU_ID = "pai-open-in-editor";
// A 1×1 transparent PNG: chrome.notifications needs an iconUrl and this
// extension ships no icon.
const NOTIFICATION_ICON =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";

const OPEN_IN_EDITOR_HOSTS = COMPANION_CONFIG?.contextMenuMatches || [];

function createOpenInEditorMenu() {
  // No hosts configured (an old companion-config.js): no menu rather than one that matches nothing.
  if (OPEN_IN_EDITOR_HOSTS.length === 0) return;
  // removeAll first: onInstalled and onStartup both call this, and creating a
  // menu id twice is an error.
  chrome.contextMenus.removeAll(() => {
    chrome.contextMenus.create({
      id: OPEN_IN_EDITOR_MENU_ID,
      title: "Open in editor",
      contexts: ["selection"],
      // The git host and CI server, where stack traces appear (the issue tracker is left out on
      // purpose). The hosts come from the generated companion-config.js.
      documentUrlPatterns: OPEN_IN_EDITOR_HOSTS,
    });
  });
}
chrome.runtime.onInstalled.addListener(createOpenInEditorMenu);
chrome.runtime.onStartup.addListener(createOpenInEditorMenu);

function notifyOpenFailed(message) {
  try {
    chrome.notifications.create({
      type: "basic",
      iconUrl: NOTIFICATION_ICON,
      title: "Couldn't open in editor",
      message: String(message).slice(0, 300),
    });
  } catch (e) {
    // Notifications unavailable — nothing more we can do quietly.
  }
}

chrome.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId !== OPEN_IN_EDITOR_MENU_ID) return;
  // info.selectionText can be cut short by Chrome for very long selections;
  // a stack-trace line is well under that limit.
  handle({ type: "open-location", text: info.selectionText || "", pageUrl: (tab && tab.url) || info.pageUrl })
    .catch((err) => notifyOpenFailed(err && err.message ? err.message : "The companion service didn't answer."));
});

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  handle(message)
    .then(sendResponse)
    .catch((err) => sendResponse({ error: err.message, details: err.details }));
  return true; // keep the message channel open for the async response above
});
